feat(app): :bricks: :memo: set up the new architecture and adding the new coding style documentation
EIP-GetOut/GETOUT-Platform pull request #14
Opened 2023-07-24 22:27 UTC by ErwanC7

2023-07-30 20:13 UTC, Happinesseuh approved these changes
Après relecture, je suis ok avec tous les points

2023-07-31 14:18 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +- In case of file containing a class that is a page, the file name **SHOULD** be the **same as the class name, but without the suffix** `page`.<br />
ça dépend avec bloc on vas probablement avoir plusieurs class (la doc devras être mis à jour)

2023-07-31 14:20 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +```dart
ce truc est débile on peut très bien mettre une licence ?

2023-07-31 14:21 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +*/
ce truc est débile on peut très bien mettre une licence dans le projet? non ?

2023-07-31 14:23 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +dart -> flutter package -> extern package -> app package <br />
flutter package et extern package on peut les regrouper c'est parreille parce que dans ce cas pourquoi ne pas séparer les packet écrit par dart du reste des imports.. fin bref 1 catégories extern et 1 catégorie intern.

2023-07-31 14:25 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +Class constructor **MUST** be **const**
if it's not possible it's OK !?

2023-07-31 14:26 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +- First brace **MUST** be in a new line.
No

2023-07-31 14:27 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +- Variable **SHOULD** be named in English.
or abbreviation.

2023-07-31 14:29 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +- Constant global variable names **MUST** be in **UPPER_SNAKE_CASE**, with no underscores and Upper case letters at the beginning of each word.
why ? https://dart.dev/tools/linter-rules/constant_identifier_names

2023-07-31 14:29 UTC, ErwanC7 commented on app/lib/coding_style.md
> +*/
A voir à la réunion de demain, j'aime bien avoir un header comme ça mais ça me dérange pas de l'enlever

2023-07-31 14:31 UTC, ErwanC7 commented on app/lib/coding_style.md
> +Class constructor **MUST** be **const**
Edit: "Class constructor SHOULD be const"

2023-07-31 14:31 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +- Function parameter **SHOULD** be **final**.
is there a case where it can't be possible or stupid ? and then I would refuse this.

2023-07-31 14:37 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +Lines **SHOULD NOT** be longer than **80 characters** but **MUST NOT** be longer than **110 characters**.
J'aurais juste décidé de supprimer cette condition de ligne et de faire confiance au gens pour ne pas dépasser 80 caractères. et si motif de laisser dépassé légèrement dans la limite du raisonnable

2023-07-31 14:37 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +Lines **SHOULD NOT** be longer than **80 characters** but **MUST NOT** be longer than **110 characters**.
je suis pas d'accord avec ces chiffres arbitraire.

2023-07-31 14:39 UTC, ErwanC7 commented on app/lib/coding_style.md
> +- Variable **SHOULD** be named in English.
Oui ce que je voulais dire dans cette phrase c'est qu'on doit réfléchir en Anglais, et donc mettre une variable qui a du sens en Anglais (je vais le rajouter si tu veux)

2023-07-31 14:39 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +_There is an exception, when a String purpose is not to be read by a human. (For example, a long URL)_
les list de valeurs constante doivent être placés/stocké dans des classes.

2023-07-31 14:40 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +**PREFER** use single quotes for String.
juste ça c'est la norme dart donc c'est évident qu'il faut faire ça. et donc single quote dans tous les cas ou cela est possible.

2023-07-31 14:41 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +_There is an exception in some widget if statement can be in one line like this :_<br >
I disagree if it can be write with brace it should

2023-07-31 14:43 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +*/
et puis on à qu'a signer une charte de confidentialité ou équivalent mdr et puis voila..

2023-07-31 14:44 UTC, ErwanC7 commented on app/lib/coding_style.md
> +- Constant global variable names **MUST** be in **UPPER_SNAKE_CASE**, with no underscores and Upper case letters at the beginning of each word.
Je sais que dart/flutter ne recommande pas cela mais c'est pour pouvoir comprendre au moment où on lit le code que la variable utiliser ne vient pas de la fonction ni de la class mais d'une global

Si je prend l'exemple du login (même si ce n'est pas le meilleur exemple car tout le monde le connais), et que je vois "rootApiPath", je vais chercher la variable dans la fonction, puis dans la class request et enfin je vais voir si elles n'est pas dans les constantes. Le but est de voir toute suite que c'est une constante global

2023-07-31 14:46 UTC, ErwanC7 commented on app/lib/coding_style.md
> +- Function parameter **SHOULD** be **final**.
Si tu parles des paramètres des fonctions, il y a écrit "should" le but est donc de mettre au maximum en final les parametres mais bien evidémment ça n'est pas toujours le cas

Si tu parles du type, je peux mettre en "should" au lieu de "must" mais je trouve ça quand même moins propre

2023-07-31 14:48 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +dart -> flutter package -> extern package -> app package <br />
de toute façon si il doit y avoir beaucoup de paquet il y en aura beaucoup et retirer les 4packet dart/flutter ne changera pas la lisibilité..

2023-07-31 14:49 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +dart -> flutter package -> extern package -> app package <br />
d'ailleurs il faut évité a tous prix d'utilisé import ... `as` ....

2023-07-31 14:50 UTC, ErwanC7 commented on app/lib/coding_style.md
> +Lines **SHOULD NOT** be longer than **80 characters** but **MUST NOT** be longer than **110 characters**.
Le but est bien évidemment de set la limite a 80 caractères mais tu peux aller jusqu'à max 110 caractères quel nombre voudrais-tu ?

2023-07-31 14:51 UTC, Perry-chouteau commented on app/lib/screens/connection/pages/login.dart
> +    } as FutureOr<void> Function(dynamic value));
peut on éviter les cast `as` ?

2023-07-31 14:52 UTC, ErwanC7 commented on app/lib/coding_style.md
> +_There is an exception, when a String purpose is not to be read by a human. (For example, a long URL)_
Une classe ApiPath qui contiendrais la liste des path de notre api par exemple ?

2023-07-31 14:53 UTC, ErwanC7 commented on app/lib/coding_style.md
> +**PREFER** use single quotes for String.
Mais le but c'est justement de faire notre normes pas de respecter la norme de truc et truc et telle truc

2023-07-31 14:54 UTC, Perry-chouteau requested changes
force Erwan <3

2023-07-31 15:09 UTC, ErwanC7 commented on app/lib/screens/connection/pages/login.dart
> +    } as FutureOr<void> Function(dynamic value));
Je ne sais pas pourquoi pendant le refacto de l'architecture, plein de requete ne marchait plus parce que l'objet n'était plus bon, comme le but premier de ce push c'était de refaire l'architecture et la norme, j'ai pas essayé de chercher plus de 30 minutes sur le problème

Donc oui il faut revoir la dessus

2023-07-31 15:12 UTC, ErwanC7 commented on app/lib/coding_style.md
> +dart -> flutter package -> extern package -> app package <br />
Ce que je te propose c'est un entre deux, ne pas couper en 4, ni en 2 mais en 3
dart/flutter -> extern -> intern
En gros cela donnerais : 
```dart
import 'dart:async';
import 'dart:html';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:http/http.dart';
import 'package:http/io.dart';
import 'package:http/test.dart';
import 'package:intl/intl.dart';

import 'package:my_app/screen/my_page.dart';
import 'package:my_app/screen/my_page.dart';
```

2023-07-31 15:21 UTC, Perry-chouteau commented on app/lib/coding_style.md
> +- First brace **MUST** be in a new line.
<img width="786" alt="Screenshot 2023-07-31 at 17 19 51" src="https://github.com/EIP-GetOut/GETOUT-Platform/assets/72015188/b4dd8a5c-c2ad-4625-8fb4-4ed896d7b160">
<img width="786" alt="Screenshot 2023-07-31 at 17 21 15" src="https://github.com/EIP-GetOut/GETOUT-Platform/assets/72015188/a3b94bca-e80b-4cfa-a103-4dd16b36c3d2">

2023-07-31 15:33 UTC, ErwanC7 commented on app/lib/coding_style.md
> +- First brace **MUST** be in a new line.
mais on s'en fout de ce qu'utilise dart je suis pas en train de pomper ce qu'a mit dart le but c'est de créer notre norme ça fait au moins 10 fois que je te le dis

Pour rappel, tu fais ce que tu veux pour les if, for, while, etc. Ici on parle seulement des fonctions

2023-07-31 20:11 UTC, closed without merging