Feature/dashboard
EIP-GetOut/GETOUT-Platform pull request #17
Opened 2023-08-22 20:34 UTC by Happinesseuh

2023-08-23 09:23 UTC, ErwanC7 requested changes
J'ai fait beaucoup de commentaire sur la norme (et encore je me suis arrêter parce que ça devenez répétitif donc du coup je te laisse check tout tes fichiers pour le header et les imports) mais y a d'autre truc qui serait bien que l'on voit tous ensemble genre le package dio, le fichier contenant toute les couleurs, etc

J'ai aussi vu que t'avais corrigé des erreurs de norme (des widgets pas en const, des traillings space, etc) dans d'autre fichier, même si y a d'autre truc qui faut qu'on revoit sur les anciens fichiers, bien joué !

Je mets en "request changes" pour que tu corriges la norme et le triple ternaire illisible mais une fois que c'est corrigé, c'est bon pour moi

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/bloc/book_event.dart
> +  String? overview;
Pourquoi il est pas en final l'overview ?

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/bloc/book_provider.dart
Il manque le header

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/bloc/book_provider.dart
> +import 'package:flutter_bloc/flutter_bloc.dart';
On est doit séparer les imports par : package dart & flutter - package externe - package interne (getout)
Je crois que le package flutter_bloc est même pas développé par les dev flutter donc il faut le compter comme un package externe

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/bloc/book_service.dart
> +    final dio = Dio();
Faudrait voir si on peut pas instancier dio d'une manière plus global mais sinon c'est ok pour moi

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/bloc/book_state.dart
vu que c'est un fichier qui est une partie d'un autre, je sais pas s'il faut qu'on mette un header (faudrait qu'on en discute)

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/pages/book.dart
> +                color: Color.fromRGBO(213, 86, 65, 0.992),
faut vraiment qu'on fasse un fichier avec toute les couleurs qu'on va utiliser parce que je pense que ça sera plus clair à lire

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/pages/book.dart
> +          Text(book.duration ?? '',
faudrait mettre un text genre "N/A" pour pas avoir juste un truc vide au niveau de l'affichage

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/pages/book_description.dart
> +                const Padding(
t'aurais pu faire un widget pour les padding en const (sauf le dernier) genre un widget comme separateLine() qui ce serait appelé title() par exemple comme ça tu gagnes des lignes et ça va dans la continuité de la lisibilité
(en vrai je le fais jamais mais c'est beaucoup plus lisible de faire des widgets avec des noms comme ça, bien joué !)

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/widgets/book_widget.dart
> +        return state.status.isSuccess
Ooof, le ternaire dans un ternaire dans un ternaire, ça fait mal
En vrai c'est peut-être plus court mais c'est vraiment illisible

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/book/widgets/book_widget.dart
Header

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/home/bloc/dashboard/dashboard_provider.dart
> +import 'package:flutter_bloc/flutter_bloc.dart';
même commentaire que toute a l'heure pour la séparation des imports

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/home/bloc/dashboard/dashboard_provider.dart
Header

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/home/widgets/books/books.dart
> +import 'package:flutter/material.dart';
séparation des imports

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/home/widgets/books/books_widget.dart
> +import 'package:getout/widgets/load_circle.dart';
les impoooooorts

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/movie/bloc/movie_provider.dart
header

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/movie/bloc/movie_service.dart
> +    final dio = Dio();
Comme je disais sur la partie des livres faut voir pour l'instance de dio

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/screens/movie/widgets/movie_widget.dart
> +        return state.status.isSuccess
même chose pour les ternaires :(

2023-08-23 09:23 UTC, ErwanC7 commented on app/lib/widgets/loading.dart
> +    bool isLandscape = (MediaQuery.of(context).size.width >
faut qu'on trouve un vrai truc pour ça parce que j'avais fait ça au début du projet mais je pense qu'il doit y avoir une variable (plus fiable) qui te dit si c'est en mode portrait ou paysage

2023-08-26 14:30 UTC, Happinesseuh commented on app/lib/screens/book/bloc/book_provider.dart
fix

2023-08-26 14:31 UTC, Happinesseuh commented on app/lib/screens/book/bloc/book_state.dart
ca reste le meme principe donc on garde le header (je les ai ajouté)

2023-08-26 14:33 UTC, Happinesseuh commented on app/lib/screens/book/pages/book_description.dart
> +                const Padding(
sachant que les child ne sont pas les mêmes un peu chiant de faire un widget juste pour ca, mais l'idée n'est pas mauvaise !

2023-08-26 14:35 UTC, Happinesseuh commented on app/lib/screens/book/bloc/book_event.dart
> +  String? overview;
Parce que de la facon dont on l'utilise le mettre en final ne va pas

2023-08-26 16:30 UTC, ErwanC7 commented on app/lib/screens/book/pages/book_description.dart
> +                const Padding(
De ce que j'ai vu si (je parle de ce en const toujours), a part pour le texte donc faudrait juste un argument au widget genre : "title(String text)" et elle fera le taff

Mais de toute façon pas obligé, c'était juste que j'aimais bien la façon dont t'avais fait le separateLine(), comme je le fait jamais (a part pour un bouton ou deux) et que je trouve que ça rend le code beaucoup plus clair, je me suis dit : "go continuer la logique"

2023-09-02 21:45 UTC, merged