feat: :sparkles: add UserPage(header, (dashboard,...),navBar, service…
EIP-GetOut/GETOUT-Platform pull request #26
Opened 2023-12-23 20:19 UTC by Perry-chouteau

… refacto) and begin genericObjectListPreview. next step: generic & put loginScreen before dashboard..

2023-12-24 03:40 UTC, ErwanC7 requested changes
En globalité, il faut revoit les headers et la norme pour les imports.

Pour le commit :
- Je rappelle pour la 95402 fois, un commit est sous cette forme "feat(target): :emoji: description"
- Mets "Home page" plutôt que "UserPage"(ça colle plus avec ce que t'as push)
- C'est fou que j'ai besoin de préciser ça mais on s'en fout des prochaines étapes, c'est un commit, pas un journal intime (tu décris ce qu'il y a dans le commit et c'est tout)

2023-12-24 03:40 UTC, ErwanC7 commented on app/macos/Flutter/GeneratedPluginRegistrant.swift
Pourquoi ce fichier a changé ?

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/movie/widgets/movie_widget.dart
les packages getout doivent être regroupé

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/services/get_out/books.dart
Je comprends pas pourquoi ce fichier est passé de "google_connection.dart" à "books.dart"

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/bloc/theme/bloc.dart
Il manque le header et les imports ne sont pas bien séparés

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/main.dart
> +          theme: themeData,
Pourquoi le thème a-t-il changé ?

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/book/widgets/book_widget.dart
> +import 'package:getout/screens/home/children/dashboard/widgets/books/books_error_widget.dart';
Faut vraiment trouver un nom à ce dossier (le dossier children)

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/bloc/home_repository.dart
> +** Wrote by Perry Chouteau  <ines.maaroufi@epitech.eu>
l'email

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/children/dashboard/bloc/books/books_bloc.dart
> +** Writed by Perry Chouteau <perry.chouteau@epitech.eu>
"Wrote" et pas "Writed"

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/children/dashboard/bloc/movies/movies_event.dart
> +** Writed by Perry Chouteau <perry.chouteau@epitech.eu>
Ne rajoute pas ton nom à chaque fois que tu changes le fichier de place ou que tu le renommes

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/bloc/like_books/like_books_bloc.dart
> +** Writed by Perry Chouteau <perry.chouteau@epitech.eu>
Si tu as fait cette faute dans la génération automatique de ton header, corrige le
Si c'est un copier-coller d'Inès, vérifie à chaque fois

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/widgets/common/cover.dart
Pas de state !!!
J'ai pas compris ce que faisait ce code par rapport au reste, mais pourquoi le widget est un Scaffold et pas laisser seulement le SizedBox ?

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/widgets/header.dart
> +import 'package:flutter/material.dart';
Sépare les 2 imports avec un espace

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/widgets/like_books/like_books_success_widget.dart
> +import 'package:flutter/material.dart';
Espace entre les 2 groupes d'import !

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/widgets/like_books/like_books_widget.dart
> +import 'package:flutter/material.dart';
Sépare les 3 groupes d'import !

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/architecture.yml
À voir avec le front en réunion ou sur Discord mais on va pas débattre de ça ici

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/architecture2.yml
je suis pas sûr de push un fichier comme ça mais si on le fait on push seulement un seul fichier architecture

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/services/service.dart
> +/**
Wow, la moitié des lignes du fichier sont pour les imports, je penses qu'un "//" au dessus des imports avec une ligne vide aurait suffit

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/services/your_books.dart
> +    final dio = Dio();
il y a déjà une variable Dio dans cette classe pourquoi en recréer une ?

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/screens/home/widgets/navbar.dart
> +import '../bloc/home_page_bloc.dart';
les imports doivent être fait de cette façon : "package:getout/path"

2023-12-24 03:40 UTC, ErwanC7 commented on app/lib/bloc/theme/bloc.dart
> +import 'default.dart';
les imports doivent être fait de cette façon : "package:getout/path"

2023-12-24 08:39 UTC, Perry-chouteau commented on app/macos/Flutter/GeneratedPluginRegistrant.swift
J'en ai aucune idée..

2023-12-28 07:04 UTC, closed without merging

2023-12-28 07:06 UTC, Perry-chouteau commented
I remove the movie/book interest on request (it's an error, I need to fix it..).