Feature/movies
EIP-GetOut/GETOUT-Platform pull request #27
Opened 2024-01-08 06:26 UTC by Happinesseuh

2024-01-08 07:56 UTC, ErwanC7 requested changes
!! LE FLUTTER ANALYZE EST PAS CLEAN !!
sinon c'est clean 👍 (bon y a quelque truc a régler quand même)

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/main.dart
> +            child: Movies(),
Je pense qu'il y a une erreur la dessus

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +//ignore: must_be_immutable
pour ne pas à avoir à mettre ce genre de commentaire qui évite le warning,  tu peux mettre les deux variables dans la fonction build (vu que de toute façon tu l'utilises que dans cette fonction) puis tu peux mettre le constructeur en const

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +          child: ListView(children: [SizedBox(height: 1000, child: const MoviesLayout())]),
pas trop fan de mettre tout sur la même ligne

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +  final dio = Dio();
a voir si on peut pas mettre une variable _dio dans la classe, l'initialiser lorsque tu rentres dans le BLoC et c'est tout

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +    dynamic movies = [];
`**ALWAYS** use **final or const** when possible and **AVOID using var or dynamic**.`
le type dynamic c'est vraiment le fourre tout, j'ai la flemme de regarder quel est le type de movies mais je pense qu'il y a moyen d'utiliser son type ou alors de le mixer avec `?` pour avoir un truc un peu plus propre

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_service.dart
dans la globalité je suis pas trop fan du `dynamic` de chaque variable qui reçoit la data, je pense que mettre le bon type puis mettre un try catch au moment où tu assignes les valeurs a la variable ça serait mieux. Comme ça si y a une erreur tu peux l'intercepter toute suite et pas au milieu du code une fois que tu te retrouves avec une variable qui a assigné des erreurs a une autre variable, qui une fois affiché vont faire crash la page

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies_liked/movies_liked_bloc.dart
> +  final MoviesRepository moviesRepository;
peut être mis en private (c'est pas un problème en soit)

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/widgets/common/cover.dart
> +  State<CoverPage> createState() => _CoverPageState();
👀

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/widgets/common/cover.dart
> +class _CoverPageState extends State<CoverPage> {
👀

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/widgets/common/cover.dart
pourquoi state ?

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/widgets/common/poster_and_description.dart
> +            child: Text(overview ?? 'Aucune description disponible',
il y a un theme qui existe déjà pour ça je crois

2024-01-08 07:56 UTC, ErwanC7 commented on app/lib/screens/movies/widgets/movies_saved/movies_saved.dart
> +    log(movies.length.toString());
je pense que c'est un oublie

2024-01-08 09:20 UTC, Perry-chouteau commented on app/lib/main.dart
> +            child: Movies(),
je suppose que c'était pour tester de toute façon je vais le changer..

2024-01-08 09:23 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +class Movies extends StatelessWidget {
La class peut tu la nommé "YourMovies" pour pas les confondres avec les widget/screen "movies" la page movie preview etc.. ? je ferais de meme avec yourBooks

2024-01-08 09:33 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +    dynamic movies = [];
utilise le meme type que pour movie, c'est la meme data entre un livre suggéré, liké ou autre/ je ferais pareil coté livre

2024-01-08 09:35 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +      '${api_constants.rootApiPath}${api_constants.getInfoMovieApiPath}/account/60eee6af-2ba2-4ff0-ba79-7c6d6c50634f/likedMovies',
pourquoi y a une url en brute ? 
c'est quoi ça ? "/60eee6af-2ba2-4ff0-ba79-7c6d6c50634f/"

2024-01-08 09:35 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +            'connect.sid=s%3ABvubf9YeIjX9sZNSMFKSlQX93ZXFziDS.DVpF1Xq%2BSPxyKMAbKfZW1Tc3jQ%2F5fcLSl%2FMtk2Glt6o'
c'est quoi ça ?

2024-01-08 09:36 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +      '${api_constants.rootApiPath}/account/fe1b3ea3-1434-4d09-8543-b00af79889d6/likedMovies',
c'est quoi ça ? ligne48, 52, 76

fe1b3ea3-1434-4d09-8543-b00af79889d6/likedMovies

2024-01-08 09:37 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +      '${api_constants.rootApiPath}/account/fe1b3ea3-1434-4d09-8543-b00af79889d6/watchlist',
etc...

2024-01-08 09:47 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +            'connect.sid=s%3ABvubf9YeIjX9sZNSMFKSlQX93ZXFziDS.DVpF1Xq%2BSPxyKMAbKfZW1Tc3jQ%2F5fcLSl%2FMtk2Glt6o'
créer une const string vu que c'est utilisé a différent endroit quand tu les auras supr la variable devra être supr pour être push sur github grace au precomit se sera plus propre que ça

2024-01-08 09:49 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +      '${api_constants.rootApiPath}${api_constants.getInfoMovieApiPath}/account/60eee6af-2ba2-4ff0-ba79-7c6d6c50634f/likedMovies',
voir l52

2024-01-08 09:50 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +      '${api_constants.rootApiPath}/account/fe1b3ea3-1434-4d09-8543-b00af79889d6/watchlist',
voir l52

2024-01-08 09:53 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +            'connect.sid=s%3ABvubf9YeIjX9sZNSMFKSlQX93ZXFziDS.DVpF1Xq%2BSPxyKMAbKfZW1Tc3jQ%2F5fcLSl%2FMtk2Glt6o'
voir l52

2024-01-08 10:00 UTC, ErwanC7 commented on app/lib/main.dart
> +            child: Movies(),
merci de supposer, sans toi jamais j'aurais deviné qu'elle testait son travail

2024-01-09 16:35 UTC, Perry-chouteau commented on app/lib/screens/movies/widgets/common/poster_and_description.dart
> +/*
encore le meme fichier

2024-01-09 18:44 UTC, Happinesseuh commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +//ignore: must_be_immutable
marche pas

2024-01-09 18:48 UTC, Happinesseuh commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +    dynamic movies = [];
j'ai pas réussi pour ca que j'ai utilisé un dynamic

2024-01-09 18:49 UTC, Happinesseuh commented on app/lib/screens/movies/widgets/common/cover.dart
> +  State<CoverPage> createState() => _CoverPageState();
?

2024-01-09 18:49 UTC, Happinesseuh commented on app/lib/screens/movies/widgets/common/cover.dart
> +class _CoverPageState extends State<CoverPage> {
?

2024-01-09 18:49 UTC, Happinesseuh commented on app/lib/screens/movies/widgets/common/cover.dart
je sais plus c'est perry qui avait ca

2024-01-09 18:50 UTC, Happinesseuh commented on app/lib/screens/movies/widgets/common/poster_and_description.dart
> +            child: Text(overview ?? 'Aucune description disponible',
pour faire quoi ?

2024-01-09 18:51 UTC, Happinesseuh commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +class Movies extends StatelessWidget {
j'aime pas du tout le nom, peut etre trouvé autre chose

2024-01-09 18:52 UTC, Happinesseuh commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +            'connect.sid=s%3ABvubf9YeIjX9sZNSMFKSlQX93ZXFziDS.DVpF1Xq%2BSPxyKMAbKfZW1Tc3jQ%2F5fcLSl%2FMtk2Glt6o'
baaaaah je suis pas désaccord avec toi, seulement ca sert a rien y a bientot le get session (enfin on espère)

2024-01-09 18:57 UTC, ErwanC7 commented on app/lib/screens/movies/widgets/common/cover.dart
> +  State<CoverPage> createState() => _CoverPageState();
C'était pour montrer le state

2024-01-09 20:06 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +class Movies extends StatelessWidget {
mais c'est le nom dans le figma

2024-01-09 20:06 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +class Movies extends StatelessWidget {
dashboard, yourBooks, yourMovies

2024-01-09 20:07 UTC, Perry-chouteau commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +            'connect.sid=s%3ABvubf9YeIjX9sZNSMFKSlQX93ZXFziDS.DVpF1Xq%2BSPxyKMAbKfZW1Tc3jQ%2F5fcLSl%2FMtk2Glt6o'
ok..

2024-01-09 22:36 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +//ignore: must_be_immutable
![image](https://github.com/EIP-GetOut/GETOUT-Platform/assets/72020065/b6aa8e42-0868-4235-8418-a2f96a789011)

2024-01-10 00:02 UTC, ErwanC7 commented on app/lib/screens/movies/widgets/movies_saved/movies_saved.dart
> +import 'dart:developer';
import non utilisé, il peut être supprimé

2024-01-10 00:02 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +// RECOMMAND
recommEnd

2024-01-10 00:02 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies_liked/movies_liked_event.dart
> +//ignore: must_be_immutable
Ça serait bien d'évité ce genre d'ignore, le but ici ça serait de mettre l'overview en final, puis dans `lib/screens/movies/bloc/movies/movies_service.dart` ligne 95 ne pas checker après que tu ai créée la réponse mais pendant (voir l'exemple en photo, je précise que c'est fix un peu moche mais t'as compris l'idée)
<img width="628" alt="image" src="https://github.com/EIP-GetOut/GETOUT-Platform/assets/72020065/6d4f41c2-7a6a-487a-a574-1ad6b8772426">

2024-01-10 00:02 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies_liked/movies_liked_event.dart
> +class MoviesLikedEvent extends Equatable {
je viens de me rendre compte que tu peux créer un constructeur en const, ce qui va te permettre de mettre tout les enfants de cette classe en const et return des const dans tes services (ici on aime les const)
<img width="504" alt="image" src="https://github.com/EIP-GetOut/GETOUT-Platform/assets/72020065/cece0483-5ba4-4d5a-80e5-a4eae3b303e0">
(je te rassure je l'ai pas fait sur mon travail non plus parce que, comme je viens de le dire, je viens juste de m'en rendre compte)

2024-01-10 00:02 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +      '${api_constants.rootApiPath}${api_constants.getInfoMovieApiPath}/${movie}',
le `${movie}`
<img width="934" alt="image" src="https://github.com/EIP-GetOut/GETOUT-Platform/assets/72020065/7beb60c9-c89b-4cab-881f-0c964c575ccb">

2024-01-10 00:02 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_service.dart
> +    print(movies[i].id);
👀

2024-01-10 00:02 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +  List<int> genreBooksIds = mapBoxMovieValuesToIds(boxBookValue);
`genreBooksIds`, cette variable est pas utilisé

2024-01-10 00:02 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies/movies_provider.dart
> +            children: [
la listes des children pourrait être en const

2024-01-10 00:15 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies_saved/movies_saved_event.dart
> +class MoviesSavedEvent extends Equatable {
Le constructeur de la classe parent en const, voir [ici](https://github.com/EIP-GetOut/GETOUT-Platform/pull/27#discussion_r1446729184) **OU** [ici](https://github.com/EIP-GetOut/GETOUT-Platform/pull/27/files#r1446729184) (ce sont les même commentaires juste selon lien où tu click, tu auras une redirection)

2024-01-10 00:15 UTC, ErwanC7 commented on app/lib/screens/movies/bloc/movies_saved/movies_saved_event.dart
> +//ignore: must_be_immutable
Enlever le "ignore", voir [ici](https://github.com/EIP-GetOut/GETOUT-Platform/pull/27#discussion_r1446725544) **OU** [ici](https://github.com/EIP-GetOut/GETOUT-Platform/pull/27/files#r1446725544) (ce sont les même commentaires juste selon lien où tu click, tu auras une redirection)

2024-01-10 00:15 UTC, ErwanC7 commented on app/lib/screens/movie/bloc/movie_event.dart
sur ce fichier il y a le même problème que sur les autres event:

Le constructeur de la classe parent en const, voir [ici](https://github.com/EIP-GetOut/GETOUT-Platform/pull/27#discussion_r1446729184) **OU** [ici](https://github.com/EIP-GetOut/GETOUT-Platform/pull/27/files#r1446729184) (ce sont les même commentaires juste selon lien où tu click, tu auras une redirection)

Enlever le "ignore", voir [ici](https://github.com/EIP-GetOut/GETOUT-Platform/pull/27#discussion_r1446725544) **OU** [ici](https://github.com/EIP-GetOut/GETOUT-Platform/pull/27/files#r1446725544) (ce sont les même commentaires juste selon lien où tu click, tu auras une redirection)

2024-01-10 20:11 UTC, merged