(Rebased) Feature/refactor logic pages when signed
EIP-GetOut/GETOUT-Platform pull request #29
Opened 2024-01-15 07:49 UTC by Perry-chouteau

2024-01-15 19:29 UTC, Happinesseuh requested changes
GG c'est clean, quelques commentaires à retirer

Je n'ai pas compris deux trois sur le code en revanche

2024-01-15 19:29 UTC, Happinesseuh commented on app/android/app/build.gradle
> +        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
pas important j'imagine le avant après ?

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/bloc/locale/bloc.dart
>  import 'package:bloc/bloc.dart';
retirer l'import pas utilisé

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/bloc/locale/bloc.dart
>  /// {@endtemplate}
ca veut dire quoi ?

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/bloc/theme/bloc.dart
> +//import 'package:flutter_bloc/flutter_bloc.dart';
same ici

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/bloc/user/bloc.dart
> +//import 'package:shared_preferences/shared_preferences.dart';
same ici

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/connection/bloc/connection_provider.dart
> +//ignore: must_be_immutable
comme avait dit erwan sur ma pr, on peut retirer ce comm et fix le pb avec des const et des finals

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/connection/services/service.dart
> +/**
pas sur que les comm comme ca rendre très clean

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/home/bloc/recommended_books/recommended_books_bloc.dart
> +      // print(stacktrace);
a enlever

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/home/children/your_books/widgets/saved_books/saved_books_widget.dart
> +            return const ObjectLoadingErrorWidget(object: 'votre reading-list');
pas sur des anglicisme

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/home/children/your_movies/widgets/saved_movies/saved_movies_widget.dart
> +            return const ObjectLoadingErrorWidget(object: 'votre watch-list');
pareil ici

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/home/pages/home_page.dart
> +///  - PageView
a retirer ?

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/home/services/movies.dart
> +        //todo return ça:
retirer les com

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/home/services/service.dart
> +  late final T t;
c'est quoi ca ?

2024-01-15 19:29 UTC, Happinesseuh commented on app/lib/screens/home/widgets/header.dart
> +          Text('La productivité à portée de main',
retirer

2024-01-16 06:01 UTC, Perry-chouteau commented on app/android/app/build.gradle
> +        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
c'est pas moi qui est écrit ça,
je les mis en todo car comme ça vous pouvez les retrouver.. 
si vous utilisé AndroidStudio vous avez la liste des Todos.
![Uploading Screenshot 2024-01-16 at 15.00.52.png…]()

2024-01-16 06:02 UTC, Perry-chouteau commented on app/lib/bloc/locale/bloc.dart
>  /// {@endtemplate}
localToEnglish
localToFrench
c'est pour changer la langue manuellement

2024-01-16 06:09 UTC, Perry-chouteau commented on app/lib/screens/connection/services/service.dart
> +/**
je vais changer le format pour 
```dart
///
```

2024-01-16 06:11 UTC, Perry-chouteau commented on app/lib/screens/home/bloc/recommended_books/recommended_books_bloc.dart
> +      // print(stacktrace);
mdr tes oublies que ta pas vraiment oublier 🤣🤣🤣🤣

2024-01-16 06:15 UTC, Perry-chouteau commented on app/lib/screens/home/children/your_books/widgets/saved_books/saved_books_widget.dart
> +            return const ObjectLoadingErrorWidget(object: 'votre reading-list');
ba je sais pas quoi mettre comme erreur.. et vu qu'on vas y retoucher rapidement quand on vas call les data du getSession. je vais ajouter dans le code
- todo changer l'erreur.

2024-01-16 06:16 UTC, Perry-chouteau commented on app/lib/constants/api_path.dart
> +  static const String token = '60eee6af-2ba2-4ff0-ba79-7c6d6c50634f';
retire ça imbécile

2024-01-16 17:11 UTC, Perry-chouteau commented on app/lib/screens/home/services/service.dart
> +  late final T t;
c'est ce qui permet de créer l'objet dio une fois et de le partager a 2 classes parentes.
sans ce trix tu est contraint a créer des instance dio partout.

2024-01-16 17:29 UTC, Perry-chouteau commented on app/lib/screens/home/children/your_movies/pages/your_movies.dart
> +          children: [RecommendedMoviesWidget(), LikedMoviesWidget(), SavedMoviesWidget()],
edit order:
recommended liked saved -> recommended saved liked.

2024-01-16 17:29 UTC, Perry-chouteau commented on app/lib/screens/home/children/your_books/pages/your_books.dart
> +          children: [RecommendedBooksWidget(), LikedBooksWidget(), SavedBooksWidget()],
edit order:
recommended liked saved -> recommended saved liked.

2024-01-16 17:52 UTC, Perry-chouteau commented on app/lib/screens/book/bloc/book_service.dart
>      try {
esque la requête ne devrais pas plutôt être dans le try

2024-01-16 17:58 UTC, Perry-chouteau commented on app/lib/screens/connection/bloc/connection_provider.dart
> +//ignore: must_be_immutable
j'ai fais un trix pour pour pas set les variables 2fois. ^^ parce que ducoup const c'était pas possible, final je pouvais pas la set 2fois et la dernier strat quand tu peux pas trix, faut ajouter/utiliser un copyWith ou la tu est complètement livre mais je voulais faire un fix rapide et au moment de set on fait 2condition qu'on pouvais faire avant et pas après

2024-01-16 18:01 UTC, Perry-chouteau commented on app/lib/screens/home/pages/home_page.dart
> +///  - PageView
c'etait de la doc pour définir le Widget mais répond moi et dis moi si tu trouve ça nul et je l'enlève

2024-01-16 18:11 UTC, Perry-chouteau commented on app/lib/screens/home/pages/home_page.dart
> +///  - PageView
la docs dart sur les commentaires de doc dart: https://dart.dev/language/comments

2024-01-18 06:19 UTC, ErwanC7 requested changes
Le fond est incroyable, ça boost l'application de fou surtout niveau code.

La forme est catastrophique t'as fait 3 choses en même temps ce qui fait qu'on se retrouve avec 150 fichiers a regarder, le coding style ne suit pas non plus et y a des fichiers dont je pensais qu'on s'était mis d'accord pour ne pas faire comme ça

Je vais être honnête sur les 20 premiers fichiers je regardais sérieusement mais en fait comme y a 3 choses mélangé c'est une horreur, donc j'ai juste survolté le reste.

Et que ce soit clair, la prochaine fois que tu mix des features en même temps je perderais même pas mon temps a regarder la pull request. Puis une fois que ça sera merge, si jamais il y a des trucs qui me plaise pas je ferais comme tu fais actuellement, c'est a dire réécrire le travail sans demander d'avis.

Encore une fois le travail reste quand même incroyable et va nous permettre de repartir sur de meilleurs "base"

2024-01-18 06:19 UTC, ErwanC7 commented on app/pubspec.lock
> +    version: "2.4.3"
de ce que je vois, tu as fait un "flutter pub upgrade", je suis pas fan d'upgrade sur un seul et même push comme ça parce qu'on a pas pu tout tester mais t'as touché tellement de chose que j'imagine que ça marche

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/bloc/user/user_data.dart
est-ce qu'on peut le mettre en const où dans le futur il y aura des data pas const ?

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/bloc/theme/bloc.dart
Pas de header et je comprends pas l'intérêt de mettre le theme en BLoC ? je trouve ça complètement overkill et juste a rendre l'app moins lisible pour rien, pour moi faut supprimer ça
(si ça permet de switch en dark mode pour le future sans devoir relancer l'app, je veux voir si y a pas un autre moyen)

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/bloc/user/bloc.dart
> +import 'package:bloc/bloc.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/docs/architecture.yml
pourquoi y a 2 versions, mets en une seule

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/book/bloc/book_event.dart
>    InfoBookResponse(
cette classe peut être en const

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/connection/bloc/connection_provider.dart
> +import 'package:flutter/material.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/connection/bloc/connection_provider.dart
Je devais refaire les BLoC moi même mais c'est pas grave

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/connection/forgot_password/bloc/forgot_password_page_state.dart
header

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/connection/forgot_password/bloc/forgot_password_provider.dart
> +import 'package:flutter_bloc/flutter_bloc.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/connection/forgot_password/children/new_password/pages/new_password_page.dart
> +import 'package:getout/screens/connection/forgot_password/children/new_password/bloc/new_password_bloc.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/connection/forgot_password/pages/forgot_password_page.dart
> +import 'package:getout/screens/connection/forgot_password/bloc/forgot_password_page_bloc.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/connection/login/widgets/fields.dart
modifier des fichier pour SEULEMENT changer des espaces c'est une perte de temps et si je commence a faire la même chose on va juste se réécrire tout nos fichiers parce que toi tu préfères cet espace et moi je préfère celui-ci.
En plus de ça, cela rajoute des fichiers a regarder alors qu'ils n'ont pas besoin d'être revu

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/bloc/books/books_event.dart
> +import 'package:getout/constants/http_status.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/bloc/home_page/home_page_event.dart
header

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/bloc/home_page/home_page_state.dart
header

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/bloc/liked_books/liked_books_bloc.dart
> +import 'package:getout/screens/home/bloc/books/books_event.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/bloc/movies/movies_event.dart
> +import 'package:getout/constants/http_status.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/dashboard/pages/dashboard.dart
> +** Wrote by Perry Chouteau <perry.chouteau@epitech.eu>
j'ai une proposition, on met ton nom partout sur tout les headers comme ça tu arrêtes de modifier les headers pour rajouter ton nom ça te va ?
Parce que dans la dernière PR que t'avais fait tu m'avais dit 'ouais mais en vrai je m'en fou" et de ce ce que je vois tu rajoute encore ton nom ou alors tu modifies encore le header donc je propose que l'on mette ton nom partout comme ça il n'y a plus de problème

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/dashboard/widgets/movies/movies_succes_widget.dart
> +import 'package:getout/screens/home/widgets/common/movie_preview_widget.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/dashboard/widgets/movies/movies_widget.dart
> -import 'package:getout/screens/home/widgets/movies/movies.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/widgets/liked_books/liked_books_success_widget.dart
> +import 'package:getout/screens/book/bloc/book_provider.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/widgets/liked_books/liked_books_widget.dart
> +import 'package:getout/tools/status.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/widgets/saved_books/saved_books_success_widget.dart
> +class SavedBooksSuccessWidget extends StatelessWidget {
peut-être mis en const si le page controller est dans la fonction

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/your_books/widgets/saved_books/saved_books_widget.dart
> +import 'package:getout/widgets/object_loading_error_widget.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/your_movies/widgets/liked_movies/liked_movies_success_widget.dart
> +import 'package:getout/screens/home/widgets/common/movie_preview_widget.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/children/your_movies/widgets/saved_movies/saved_movies_success_widget.dart
> +import 'package:getout/screens/home/widgets/common/movie_preview_widget.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/pages/home_page.dart
> +import 'package:getout/screens/home/bloc/home_page/home_page_bloc.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/widgets/navbar.dart
> +import '../bloc/home_page/home_page_bloc.dart';
fait un import classique

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/widgets/recommended_books/recommended_books_widget.dart
> +import 'package:getout/screens/home/bloc/recommended_books/recommended_books_bloc.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/widgets/recommended_movies/recommended_movies_success_widget.dart
> +import 'package:getout/screens/home/widgets/common/movie_preview_widget.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/widgets/recommended_movies/recommended_movies_success_widget.dart
> +  RecommendedMoviesSuccessWidget({
peut-être mit en const sur le page controller était dans la fonction

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/home/widgets/recommended_movies/recommended_movies_widget.dart
> +import 'package:getout/screens/home/widgets/recommended_movies/recommended_movies_success_widget.dart';
coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/screens/movie/widgets/movie_widget.dart
header + coding style

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/services/get_out/service.dart
ce fichier n'a pas de header et je pensais que la finalité c'était qu'on séparait pas les services

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/services/get_out/settings.dart
je pensais que la finalité c'était qu'on séparait pas les services

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/services/get_out/sign.dart
je pensais que la finalité c'était qu'on séparait pas les services

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/tools/status.dart
> +** Wrote by Erwan Cariou <erwan1.cariou@epitech.eu>
je savais pas que j'avais écrit ce fichier

2024-01-18 06:19 UTC, ErwanC7 commented on app/lib/widgets/show_snackbar.dart
pas de header

2024-01-18 06:21 UTC, ErwanC7 commented
je précise aussi : on fera un squash de cette branch car aucun des commits que tu as fais n'est propre

2024-01-19 08:11 UTC, Perry-chouteau commented on app/lib/services/get_out/settings.dart
fait un schema

2024-01-19 08:21 UTC, Perry-chouteau commented on app/lib/services/get_out/service.dart
ok ba je vais tout regrouper dans ce cas..

2024-01-19 09:20 UTC, Perry-chouteau commented on app/lib/bloc/user/bloc.dart
> +import 'package:bloc/bloc.dart';
quesqui ne vas pas ?

2024-01-19 09:30 UTC, Perry-chouteau commented on app/lib/bloc/user/user_data.dart
stp sélectionne des lignes les prochaines fois..

2024-01-19 09:32 UTC, Perry-chouteau commented on app/lib/bloc/theme/bloc.dart
pour gérer le light et darkmode c'est comme ça qu'il faut faire.

2024-01-19 09:42 UTC, Perry-chouteau commented on app/lib/services/get_out/settings.dart
ba si tu veut mettre les bloc dans l'ui les services doivent suivre ça...

2024-01-19 09:43 UTC, Perry-chouteau commented on app/lib/services/get_out/sign.dart
2 si tu veut mettre les bloc dans l'ui les services doivent suivre ça...

2024-01-19 09:44 UTC, Perry-chouteau commented on app/lib/tools/status.dart
> +** Wrote by Erwan Cariou <erwan1.cariou@epitech.eu>
peut être xD

2024-01-19 18:13 UTC, ErwanC7 commented on app/lib/bloc/user/user_data.dart
il y a que deux possibilité, la classe ou la variable, je dis "il y aura des datas" donc pour moi ça pointé vers la classe, mais en vrai t'as raison ça évite de jouer a la devinette comme sur mon commentaire

2024-01-19 18:16 UTC, ErwanC7 commented on app/lib/bloc/theme/bloc.dart
NON c'est pas comme ça qu'il faut faire, en 30 secondes de recherche j'ai trouvé la réponse :
<img width="572" alt="image" src="https://github.com/EIP-GetOut/GETOUT-Platform/assets/72020065/e5fd8f18-507b-45ee-b3c8-9e146d38f31a">

2024-01-19 18:18 UTC, ErwanC7 commented on app/lib/bloc/user/bloc.dart
> +import 'package:bloc/bloc.dart';
les imports ne sont pas bon (TU PEUX PAS METTRE EN "RESOLVE" SI TU SAIS MÊME D'OÙ VIENT L'ERREUR)

2024-01-19 20:38 UTC, Perry-chouteau commented on app/lib/bloc/user/bloc.dart
> +import 'package:bloc/bloc.dart';
en quoi l'import est mauvais ???? wtf

2024-01-19 20:50 UTC, Perry-chouteau commented on app/lib/bloc/theme/bloc.dart
<img width="1109" alt="Screenshot 2024-01-20 at 05 48 46" src="https://github.com/EIP-GetOut/GETOUT-Platform/assets/72015188/bbbba45b-4642-4669-bbbb-cd88e4fda2e5">

2024-01-19 21:09 UTC, ErwanC7 commented on app/lib/bloc/theme/bloc.dart
plus simple avec ta version on garde ça comme tu as fais

2024-01-20 01:53 UTC, ErwanC7 approved these changes

2024-01-20 02:47 UTC, merged