Feature/notifications
EIP-GetOut/GETOUT-Platform pull request #30
Opened 2024-01-15 19:45 UTC by Happinesseuh

2024-01-18 01:15 UTC, ErwanC7 requested changes
Pas mal d'erreur pour peu de fichier, je te conseille vraiment d'utiliser android studio ça évite ce genre de problème

2024-01-18 01:15 UTC, ErwanC7 commented on app/lib/main.dart
> +            child: WelcomePage(),
Pourquoi avoir changer ça ?
Cette page est en plus déprécié il faut la supprimer. Je l'ai oublié (j'ai pas voulu touché la partie form)

2024-01-18 01:15 UTC, ErwanC7 commented on app/lib/screens/settings/pages/notifications/notifications.dart
Pas de header + le package timezone est utilisé ici mais il n'a pas été importé dans le pubspec.yaml

2024-01-18 01:15 UTC, ErwanC7 commented on app/lib/screens/settings/pages/notifications/notifications_page.dart
pas de header + pourquoi la classe est en state management ?

2024-01-18 01:21 UTC, ErwanC7 commented
je viens de remarqué aussi quand je fais un flutter pub get pour générer le pubspec.lock, j'ai "pubspec.lock" et "windows/flutter/generated_plugins.cmake" qui on été modifié et qui sont marqué comme différent de la version sur GitHub (donc il faudrait les push)

2024-01-18 02:26 UTC, Happinesseuh commented on app/lib/screens/settings/pages/notifications/notifications_page.dart
obliger pour utiliser le set state

2024-01-18 02:30 UTC, ErwanC7 commented on app/lib/screens/settings/pages/notifications/notifications_page.dart
On en avait discuté avec Perry, normalement il y est censé avoir un BLoC relié a cette page et c'est la valeur de ce BLoC qui est relié et mis a jour a chaque fois (si mon explication est pas très claire je peux te montrer un exemple)

2024-01-18 02:31 UTC, Happinesseuh commented on app/lib/screens/settings/pages/notifications/notifications_page.dart
oui et on a déjà parlé que tant que la page settings est pas faites je peux pas faire la page notifications en mode bloc

2024-01-18 02:38 UTC, ErwanC7 approved these changes

2024-01-18 19:33 UTC, Perry-chouteau commented on app/lib/main.dart
> +  runApp(const MyApp());}
1) Middleware
2) mais l'accolade du main à la ligne

2024-01-18 19:34 UTC, Perry-chouteau commented on app/lib/global.dart
> +NotificationsServices notificationsServices = NotificationsServices();
J'aime pas voir ce fichier et encore voire des chose apparaitre dedans..
c'est obliger tu peux pas faire un NotificationBloc ?

2024-01-18 19:36 UTC, Happinesseuh commented on app/lib/main.dart
> +  runApp(const MyApp());}
middleware ?? j'ai pas touché ca

2024-01-18 19:36 UTC, Happinesseuh commented on app/lib/global.dart
> +NotificationsServices notificationsServices = NotificationsServices();
Un sujet déjà abordé avec Erwan, le soucis étant que les settings ne sont pas en mode bloc, donc compliqué d'intégrer les notifications en mode bloc... malheuresement on en revient toujours au même soucis...

2024-01-18 19:43 UTC, Perry-chouteau commented on app/lib/global.dart
> +NotificationsServices notificationsServices = NotificationsServices();
ok pas de soucis si c'est pas fait je me porterais volontaire pour le faire le sprint prochain

2024-01-18 19:44 UTC, Perry-chouteau commented on app/lib/main.dart
> +  runApp(const MyApp());}
weird xD

2024-01-18 19:45 UTC, Perry-chouteau commented on app/lib/main.dart
> +  runApp(const MyApp());}
moi de mon coté j'ai la bonne écriture il me semble, donc quand j'aurais PR, je sais pas ce que sera le résultat ^^'

2024-01-18 19:51 UTC, Happinesseuh commented on app/lib/main.dart
> +  runApp(const MyApp());}
je vais edit dans tous les cas

2024-01-20 07:40 UTC, ErwanC7 commented on app/lib/screens/settings/pages/notifications/notifications.dart
> +  bool firstRun = false;
les 2 variables peuvent être mis en private (en plus y a un getter après)

2024-01-20 07:40 UTC, ErwanC7 commented on app/lib/screens/settings/pages/notifications/notifications.dart
> +import 'package:flutter/material.dart';
séparation entre les packages flutter et les packages externe

2024-01-20 07:47 UTC, ErwanC7 commented on app/lib/main.dart
>    Bloc.observer = const AppBlocObserver(); // BLoC MidleWare.
J'en profite, juste pour corriger ça : `// BLoC MiddleWare` (MiddleWare avec 2 d)

2024-01-20 08:54 UTC, Perry-chouteau commented on app/lib/screens/settings/pages/notifications/notifications.dart
> +  bool firstRun = false;
c'est pas possible elle sont init dans des async function et non pas dans le constructor.

2024-01-21 03:46 UTC, merged