fix(app): :boom: :art: :zap: build settings(edit_password,edit_email) with lightweight architecture <3
EIP-GetOut/GETOUT-Platform pull request #45
Opened 2024-03-17 15:42 UTC by Perry-chouteau

- update doc
- remove variable globalEmail
- I know I need to remove and fix a lot of things (print, etc..) but wanna get some feedback on settings (edit_password, edit_mail).

2024-03-17 15:47 UTC, Perry-chouteau commented on app/lib/widgets/button/floating_button.dart
> +
Petit floatingButtonWidget utilisable normalement partout.

2024-03-17 15:47 UTC, Perry-chouteau commented on app/lib/widgets/fields/email_field.dart
> +
voir ce fichier + DEFAULT_FIELD

2024-03-17 15:49 UTC, Perry-chouteau commented on app/lib/widgets/fields/email_field.dart
> +}
voir ce fichier + DEFAULT_FIELD

2024-03-17 15:50 UTC, Perry-chouteau commented on app/lib/widgets/fields/password_field.dart
> +}
voir ce 2eme fichier + DEFAULT_FIELD

2024-03-17 15:50 UTC, Perry-chouteau commented on app/lib/widgets/fields/widgets/default_field.dart
> +}
default_field

2024-03-17 15:50 UTC, Perry-chouteau commented on app/lib/widgets/fields/widgets/title_field.dart
> +Widget fieldTitle(final String title, bool mandatory) {
title_field

2024-03-17 15:51 UTC, Perry-chouteau commented on app/lib/widgets/fields/code_field.dart
> +import 'package:flutter/material.dart';
voir ce fichier + DEFAULT_FIELD

2024-03-17 15:54 UTC, Perry-chouteau commented on app/lib/screens/settings/services/session.dart
> +class SessionEvent extends Equatable {
bon j'ai créer des event dans l'idée de faire un bloc mais je vais simplifier ça en simple argument de fonction.
services comme on dit (si je viennais a garder les struct on oublie pas le fichier (x)event pour les struct comme indiqué dans la doc)

2024-03-17 15:56 UTC, Perry-chouteau commented on app/lib/screens/settings/pages/edit_email/edit_mail.dart
> +}
implémentation de <X>Field hériter de defaultField. utilisé dans edit mail (voir aussi edit_password)

2024-03-17 15:57 UTC, Perry-chouteau commented on app/lib/screens/settings/pages/edit_password/edit_password.dart
> +
implémentation de <X>Field hériter de defaultField. utilisé dans edit password (voir aussi edit_mail)

2024-03-18 04:00 UTC, Happinesseuh requested changes

2024-03-18 04:00 UTC, Happinesseuh commented on app/lib/constants/api_path.dart
> +    ? /*'http://10.0.2.2:8080'*/ 'http://192.168.0.3:8080'
remet le 10.0.2.2

2024-03-18 04:00 UTC, Happinesseuh commented on app/lib/screens/settings/pages/notifications/notifications.dart
> +        InitializationSettings(android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
pourquoi mettre ios alors que le projet ne le sera jamais ?

2024-03-19 20:43 UTC, Perry-chouteau commented on app/lib/screens/settings/pages/notifications/notifications.dart
> +        InitializationSettings(android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
ba ducoup je laisse au pire on l'enlèvera si non nécéssaire..

2024-03-20 00:53 UTC, Perry-chouteau commented on app/lib/screens/connection/login/pages/login.dart
> +        body: BlocListener<LoginBloc, LoginState>(
cancel

2024-03-20 20:39 UTC, Happinesseuh commented on app/lib/screens/settings/pages/edit_email/edit_mail.dart
> +      builder: (context) => AlertDialog(
peut-on retirer le code commenté si il ne sert a rien ?

2024-03-20 20:39 UTC, Happinesseuh commented on app/lib/screens/settings/pages/edit_password/edit_password.dart
> +        actions: [
same ici

2024-03-20 21:43 UTC, ErwanC7 reviewed
"On a jamais vu une PR aussi propre venant de Perry" - Forbes

2024-03-20 21:43 UTC, ErwanC7 commented on app/lib/screens/settings/settings.dart
> +  State<SettingsPage> createState() => _SettingsPageState();
du coup on la met sous la forme state ? (vrai question)

2024-03-20 21:43 UTC, ErwanC7 commented on app/lib/widgets/button/floating_button.dart
> +** Wrote by Erwan Cariou <erwan1.cariou@epitech.eu>
carrément j'ai co écrit ce fichier

2024-03-20 22:19 UTC, Perry-chouteau commented on app/lib/widgets/button/floating_button.dart
> +** Wrote by Erwan Cariou <erwan1.cariou@epitech.eu>
parceque j'ai repris ton code..

2024-03-20 22:19 UTC, Perry-chouteau commented on app/lib/screens/settings/settings.dart
> +  State<SettingsPage> createState() => _SettingsPageState();
non surtout pas

2024-03-20 22:20 UTC, Perry-chouteau commented on app/lib/screens/settings/settings.dart
> +  State<SettingsPage> createState() => _SettingsPageState();
![Uploading CleanShot 2024-03-21 at 07.20.35@2x.png…]()

J'ai corriger

2024-03-21 12:33 UTC, Perry-chouteau commented
@Happinesseuh tu me bloque je peux rien faire..

2024-03-21 14:29 UTC, merged