Feature/generic input
EIP-GetOut/GETOUT-Platform pull request #76
Opened 2024-07-03 14:35 UTC by Happinesseuh

2024-07-03 21:00 UTC, Perry-chouteau commented on app/lib/widgets/fields/widgets/default_field.dart
> +class DefaultField extends StatefulWidget {
utilise des changeNotifier ou des valueListener et remet en stateless?

2024-07-03 22:36 UTC, ErwanC7 requested changes
- Une des carte de Perry dans un des sprints était de mettre en place le texte dans un seul est même fichier (L10n), j'ai vu qu'a plein d'endroit tu as enlevé ce systeme de texte pour mettre du texte en brute, faut fixer ça avant de le merge
- Il faut fix le problème du message du validator qui est trop long

2024-07-03 22:36 UTC, ErwanC7 commented on app/lib/screens/connection/login/pages/login.dart
> +            showSnackBar(context, 'Vos identifiants sont incorrects');
c'est pas bon le fix n'est pas correct, dans tout les erreurs possible (même celle qu'on prevoit pas) tu afficheras qu'il y a un probleme d'identifiants

2024-07-03 22:36 UTC, ErwanC7 commented on app/lib/screens/connection/register/bloc/register_service.dart
comme j'ai déjà dit a Perry ça sert a rien de modifier des fichiers juste pour modifier le style du code, ça rajoute des fichiers dans la PR pour rien
(surtout que je vois que tu es passé du coté obscure de la force, tu mets tes accolades sur la même ligne)

2024-07-03 22:36 UTC, ErwanC7 commented on app/lib/screens/connection/register/widgets/fields.dart
> +                        labelText: 'Entrez votre date',
*votre date de naissance (Perry avait déjà fait un text avec L10n)

2024-07-03 22:36 UTC, ErwanC7 commented on app/lib/widgets/fields/password_field.dart
Pour le password il y a un problème, le message est trop long donc on peut pas voir l'erreur complète, mais en essayant de le régler tu vas surrement avoir un problème (trop long a expliquer, je te ferais un vocal sur discord) je sais pas comment s'était géré dans l'inscription avant mais pour le changement de mot de passe j'avais laissé plus d'espace a cause de ça
<img width="279" alt="image" src="https://github.com/EIP-GetOut/GETOUT-Platform/assets/72020065/5b53c9b4-4f16-4594-b0b0-0748fbd0258c">

2024-07-03 22:36 UTC, ErwanC7 commented on app/lib/widgets/fields/widgets/default_field.dart
> +class _DefaultFieldState extends State<DefaultField> {
je croyais qu'on essayait de plus utiliser le State ?

2024-07-03 22:36 UTC, ErwanC7 commented on app/lib/widgets/fields/widgets/default_field.dart
> +              fillColor: const Color(0xffeaeaea),
est-ce qu'on mettrait pas la couleur dans le thème ?

2024-07-04 02:08 UTC, Happinesseuh commented on app/lib/screens/connection/register/bloc/register_service.dart
Pas volontaire, des fois je suis sur un fichier que j'edit et je fais "format document" sur flutter, ca arrive que je le fasse sur des fichiers pas edit au final, je peux le restore

2024-07-04 02:10 UTC, Happinesseuh commented on app/lib/widgets/fields/password_field.dart
J'ai vraiment laisser comme c'était avant que je récupère, maintenant on peut essayer d'afficher l'erreur sur plusieurs lignes à voir comment faire

2024-07-04 02:11 UTC, Happinesseuh commented on app/lib/widgets/fields/widgets/default_field.dart
> +class DefaultField extends StatefulWidget {
En quoi le stateful est gênant ?

2024-07-04 02:11 UTC, Happinesseuh commented on app/lib/widgets/fields/widgets/default_field.dart
> +class _DefaultFieldState extends State<DefaultField> {
J'utilise un use state j'avais las le choix, maintenant perry à l'air de dire qu'on peut faire autrement, mais si c'est trop chiant ca reste en stateful

2024-07-04 02:18 UTC, ErwanC7 commented on app/lib/screens/connection/register/bloc/register_service.dart
non pas besoin c'est juste faut faire attention avant de push

2024-07-04 02:23 UTC, ErwanC7 commented on app/lib/widgets/fields/password_field.dart
justement c'est un des problemes que j'avais sur le changement de mot de passe, j'avais un fix qui était applicable dans mon cas, en faisant ce generic input le but c'est que ça soit clean partout et pas que dans une des partie

2024-07-05 18:34 UTC, ErwanC7 approved these changes

2024-07-05 19:31 UTC, merged