feat(app): :sparkles: add email verification with code, with page suc…
EIP-GetOut/GETOUT-Platform pull request #82
Opened 2024-07-17 10:39 UTC by Happinesseuh

…ess and redirection to dashboard or forms, add a button to resend email if needed with a cooldown

2024-07-17 16:04 UTC, Perry-chouteau commented on app/lib/l10n/app_fr.arb
> +  "code_mail_hint": "Entrer le code reçu par mail",
utilise code_hint au lieu de créer une autre variable.. c'est le meme principe dans le 2cas c'est un mail que tu reçois si la phrase ne te convient pas et que tu veux le truc plus long (plus long c'est un risque d'overflow) change la phrase :) .

2024-07-17 20:26 UTC, ErwanC7 requested changes

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/l10n/app_en.arb
> +  "code_incorect": "The code is incorrect",
c'est en double nan ?

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/l10n/app_fr.arb
> +  "email_verification_hint": "Entrez le code de confirmation reçue par mail",
entrez ou entrer ? faut qu'on se mette d'accord, pour moi on le met sous la forme "ez" (+ Email et pas mail)

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/l10n/app_fr.arb
> +  "email_verification_resend": "Renvoyez l'email",
Je pense que mettre "Renvoyer un code" fait plus naturel

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/l10n/app_fr.arb
> +  "email_verification_success": "Votre adresse mail a bien été confirmé",
"Votre adresse email" (et pas mail)

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/l10n/app_en.arb
> +  "password_actual_empty": "Please enter your current password",
c'est en double je crois

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/main.dart
> +          builder: (context, state) {
Je pense que faudrait faire un switch case ça commence a faire beaucoup de if
(Je sais déjà ce que tu vas me répondre donc je preshot: je sais que ça fait pas parti de ton travail, je commente ça pour Perry)

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/screens/connection/email_verified/bloc/email_verified_event.dart
> +  EmailVerifiedCodeChanged({this.code});
const !!!

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/screens/connection/email_verified/bloc/email_verified_state.dart
> +  bool get isCodeValid => code.isNotEmpty && true;// code.length == 6;
J'ai pas compris l'interet du "&& true"

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/screens/connection/email_verified/pages/email_verified_page.dart
> +import 'dart:async';
Il manque le header !

2024-07-17 20:26 UTC, ErwanC7 commented on app/lib/screens/connection/services/sign.dart
> +                'salt': 'sdjqshjodijaoz'
J'en profite que t'es touchée ce fichier, y a moyen que tu retires le 'salt' stp ?

2024-07-18 13:58 UTC, Happinesseuh commented on app/lib/l10n/app_fr.arb
> +  "code_mail_hint": "Entrer le code reçu par mail",
j'ai juste rename code_mail_hint car le @ faisait que des dingueries de syntax + il n'etait pas utilisé donc comme ca c'est good

2024-07-18 13:58 UTC, Happinesseuh commented on app/lib/l10n/app_en.arb
> +  "code_incorect": "The code is incorrect",
oui avec une faute en + mdrrr, je fix ca !

2024-07-18 14:20 UTC, Happinesseuh commented on app/lib/screens/connection/email_verified/bloc/email_verified_event.dart
> +  EmailVerifiedCodeChanged({this.code});
je me suis basé sur le new password pour pas changer trop de syntax + je suis obligé pour recvoir le code (cf new_password_event)

2024-07-18 14:21 UTC, Happinesseuh commented on app/lib/screens/connection/email_verified/bloc/email_verified_state.dart
> +  bool get isCodeValid => code.isNotEmpty && true;// code.length == 6;
encore une fois je me suis basé sur le new password

2024-07-18 22:13 UTC, ErwanC7 commented on app/lib/l10n/app_en.arb
> +  "password_actual_empty": "Please enter your current password",
les noms changent mais ce sont exactement les mêmes

2024-07-18 22:13 UTC, ErwanC7 commented on app/lib/screens/connection/email_verified/bloc/email_verified_event.dart
> +  EmailVerifiedCodeChanged({this.code});
Si j'ai fais des erreurs sur new password faut pas les recopier ! (et je vois pas pourquoi t'es obligée, suffit juste de mettre la super class en const aussi)

2024-07-18 22:21 UTC, ErwanC7 commented on app/lib/screens/connection/email_verified/bloc/email_verified_state.dart
> +  bool get isCodeValid => code.isNotEmpty && true;// code.length == 6;
Si j'ai fais des erreurs sur new password faut pas les recopier !

2024-07-18 22:21 UTC, ErwanC7 commented on app/lib/screens/connection/email_verified/bloc/email_verified_state.dart
> +  bool get isCodeValid => code.isNotEmpty && true;// code.length == 6;
Si j'ai fais des erreurs sur new password faut pas les recopier !

2024-07-18 22:49 UTC, ErwanC7 approved these changes

2024-07-25 08:23 UTC, merged