fix(app): :sparkles: replace dio & persistentCookie from globals by a simple string instead.
EIP-GetOut/GETOUT-Platform pull request #84
Opened 2024-08-14 16:34 UTC by Perry-chouteau

2024-08-16 15:40 UTC, Happinesseuh requested changes

2024-08-16 15:40 UTC, Happinesseuh commented on app/lib/global.dart
> +bool isCookieSet = false;
pourquoi remplacer le cookiejar par une string ??? Quel est l'interet ??

2024-08-16 15:40 UTC, Happinesseuh commented on app/lib/screens/connection/register/bloc/register_service.dart
> +    dio.options.headers = ({'Content-Type': 'application/json'});
et donc a chaque fois on refait ca ?? mais pourquoi ??? on gagne du temps avec la global ca n'a pas d'interet

2024-08-16 15:40 UTC, Happinesseuh commented on app/lib/screens/movie/bloc/movie_service.dart
> +    dio.options.headers = ({'Content-Type': 'application/json'});
15 ème fois qu'on recopie ces 4 mêmes lignes pour éviter d'utiliser une global....

2024-08-16 20:09 UTC, Perry-chouteau commented on app/lib/screens/connection/register/bloc/register_service.dart
> +    dio.options.headers = ({'Content-Type': 'application/json'});
on récupèrent des dio non-nullable
ça permet d'être sur d'avoir dio et le cookie set. et cela fait des réponses non-nullable

2024-08-16 20:11 UTC, Perry-chouteau commented on app/lib/screens/movie/bloc/movie_service.dart
> +    dio.options.headers = ({'Content-Type': 'application/json'});
inès les services que j'ai relié dans des groupes de service ont pourais améliorer le code pour écrire ces lignes uniquement dans le constructeur de groupe.

2024-08-16 20:13 UTC, Perry-chouteau commented on app/lib/global.dart
> +bool isCookieSet = false;
expliquer en dessous

2024-08-18 09:24 UTC, Happinesseuh approved these changes

2024-08-19 10:57 UTC, merged